version: "3"

services:
  server:
    build: server
    mem_limit: 512m
    ports:
      - 8761:8761
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s  
    networks:
      - my-network

  gateway:
    build: gateway
    mem_limit: 512m
    ports:
      - 8444:8444
    environment:
      ALIAS: nicotole
      CERT_PASS: toletole12
      EUREKA: http://server:8761/eureka/      
    restart: always
    depends_on:
      server:
        condition: service_healthy
    networks:
      - my-network

  central:
    build: central
    mem_limit: 512m
    ports:
      - 8180:8180
    environment:
      EUREKA: http://server:8761/eureka/
      BD_USER: vps3_root
      BD_PASSWORD: 123
      BD_URL: jdbc:mysql://vps-3858808-x.dattaweb.com:3306/vps3_cursoReact?serverTimezone=UTC
      PRIVATE_KEY: f4e5d3bad303c742f671fbf03518e9bc94adf6921eacb60c1074496e143e3ce0
      SS_PASSWORD: 1234
      SS_USER: todocode
      USER_GENERATOR: TODOCODE-SEC
    restart: always
    depends_on:
      server:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge